export interface Testimonial {
  name: string;
  game: string;
  rating: number;
  comment: string;
  date: string;
  avatar: string;
}

export const testimonials: Testimonial[] = [
  // ═══════════════════════════════════════
  // MOBILE LEGENDS (30 testimoni)
  // ═══════════════════════════════════════
  { name: "Rizky A.", game: "Mobile Legends", rating: 5, comment: "Top up diamond ML cepet banget, belum 1 menit udah masuk!", date: "10 Mar 2026", avatar: "🎮" },
  { name: "Dinda S.", game: "Mobile Legends", rating: 5, comment: "Harganya paling murah dibanding toko lain, langganan sini terus 🔥", date: "9 Mar 2026", avatar: "💎" },
  { name: "Farel P.", game: "Mobile Legends", rating: 5, comment: "Baru pertama top up disini, ternyata beneran amanah. Recommended!", date: "8 Mar 2026", avatar: "⭐" },
  { name: "Ayu M.", game: "Mobile Legends", rating: 4, comment: "Proses cepat, admin ramah. Cuma harus upload bukti dulu ya, tapi aman kok", date: "7 Mar 2026", avatar: "🌸" },
  { name: "Bagas R.", game: "Mobile Legends", rating: 5, comment: "Udah 5x top up disini, ga pernah kecewa. Mantap!", date: "6 Mar 2026", avatar: "🏆" },
  { name: "Nisa W.", game: "Mobile Legends", rating: 5, comment: "Harga weekly diamond murah banget disini, jadi langganan", date: "5 Mar 2026", avatar: "💖" },
  { name: "Aldi K.", game: "Mobile Legends", rating: 5, comment: "Starlight bulanan selalu top up disini, fast respond admin", date: "4 Mar 2026", avatar: "🌟" },
  { name: "Putri L.", game: "Mobile Legends", rating: 4, comment: "Awalnya ragu, tapi ternyata beneran masuk diamond-nya!", date: "3 Mar 2026", avatar: "🎀" },
  { name: "Rendi J.", game: "Mobile Legends", rating: 5, comment: "Top up buat push rank, diamond langsung masuk. GG!", date: "2 Mar 2026", avatar: "⚔️" },
  { name: "Siti H.", game: "Mobile Legends", rating: 5, comment: "Beli skin collector pake diamond dari sini, murah pol!", date: "1 Mar 2026", avatar: "👑" },
  { name: "Yoga A.", game: "Mobile Legends", rating: 5, comment: "Admin response cepet, diamond masuk kurang dari 3 menit", date: "28 Feb 2026", avatar: "⚡" },
  { name: "Dewi P.", game: "Mobile Legends", rating: 5, comment: "Bayar pake QRIS gampang banget, diamond instan!", date: "27 Feb 2026", avatar: "💳" },
  { name: "Ilham R.", game: "Mobile Legends", rating: 5, comment: "Transfer bank juga bisa, proses tetep cepet!", date: "26 Feb 2026", avatar: "🏦" },
  { name: "Laras B.", game: "Mobile Legends", rating: 5, comment: "Beli starlight tiap bulan disini, harga stabil murah", date: "25 Feb 2026", avatar: "🌟" },
  { name: "Citra A.", game: "Mobile Legends", rating: 5, comment: "Recommended banget! Udah 10x lebih top up disini", date: "24 Feb 2026", avatar: "❤️" },
  { name: "Nadia S.", game: "Mobile Legends", rating: 5, comment: "Harga diamond termurah yang pernah saya temuin!", date: "23 Feb 2026", avatar: "💰" },
  { name: "Galang T.", game: "Mobile Legends", rating: 5, comment: "Beli twilight pass langsung masuk, seneng banget!", date: "22 Feb 2026", avatar: "🌅" },
  { name: "Ratna D.", game: "Mobile Legends", rating: 4, comment: "Sempet nunggu 10 menit tapi akhirnya masuk juga, tetep oke", date: "21 Feb 2026", avatar: "⏰" },
  { name: "Surya W.", game: "Mobile Legends", rating: 5, comment: "Top up diamond buat event KOF, harga disini paling worth it", date: "20 Feb 2026", avatar: "🥊" },
  { name: "Fitri N.", game: "Mobile Legends", rating: 5, comment: "Diamond 2x lipat event, top up disini murah banget jadinya", date: "19 Feb 2026", avatar: "🎊" },
  { name: "Doni M.", game: "Mobile Legends", rating: 5, comment: "Proses otomatis, tinggal bayar langsung masuk. Top!", date: "18 Feb 2026", avatar: "🤖" },
  { name: "Winda K.", game: "Mobile Legends", rating: 5, comment: "Beli diamond buat gift temen, prosesnya gampang banget", date: "17 Feb 2026", avatar: "🎁" },
  { name: "Arya P.", game: "Mobile Legends", rating: 5, comment: "Langganan setia, udah ga mau pindah ke toko lain", date: "16 Feb 2026", avatar: "🔒" },
  { name: "Lestari S.", game: "Mobile Legends", rating: 4, comment: "Admin bales agak lama tapi diamond tetep masuk, aman", date: "15 Feb 2026", avatar: "📱" },
  { name: "Hadi G.", game: "Mobile Legends", rating: 5, comment: "Top up tengah malam juga bisa, 24 jam nonstop!", date: "14 Feb 2026", avatar: "🌙" },
  { name: "Rina V.", game: "Mobile Legends", rating: 5, comment: "Harga 86 diamond cuma 20rb, murah parah!", date: "13 Feb 2026", avatar: "💸" },
  { name: "Bima F.", game: "Mobile Legends", rating: 5, comment: "Udah rekomendasi ke semua temen squad, semuanya puas!", date: "12 Feb 2026", avatar: "👥" },
  { name: "Sinta R.", game: "Mobile Legends", rating: 5, comment: "Weekly diamond pass beli disini aja, paling murah se-Indonesia", date: "11 Feb 2026", avatar: "🏅" },
  { name: "Dimas H.", game: "Mobile Legends", rating: 5, comment: "Skin epic baru langsung kebeli, makasih Lapak Robux!", date: "10 Feb 2026", avatar: "✨" },
  { name: "Novi T.", game: "Mobile Legends", rating: 5, comment: "Top up via DANA bisa, OVO bisa, lengkap banget!", date: "9 Feb 2026", avatar: "💝" },

  // ═══════════════════════════════════════
  // ROBLOX (25 testimoni)
  // ═══════════════════════════════════════
  { name: "Zahra K.", game: "Roblox", rating: 5, comment: "Beli robux buat anak, delivery cepet dan aman!", date: "10 Mar 2026", avatar: "🧸" },
  { name: "Rangga S.", game: "Roblox", rating: 5, comment: "Robux murah banget disini, udah langganan dari lama", date: "9 Mar 2026", avatar: "🎲" },
  { name: "Anisa R.", game: "Roblox", rating: 5, comment: "Anak saya seneng banget dapet robux cepet, thx Lapak Robux!", date: "8 Mar 2026", avatar: "🎈" },
  { name: "Budi P.", game: "Roblox", rating: 4, comment: "Pertama kali beli disini, prosesnya gampang dan aman", date: "7 Mar 2026", avatar: "🎪" },
  { name: "Mega V.", game: "Roblox", rating: 5, comment: "Harga robux paling murah se-Indonesia! Top banget", date: "6 Mar 2026", avatar: "🌈" },
  { name: "Hafiz M.", game: "Roblox", rating: 5, comment: "Robux langsung masuk, bisa beli gamepass favorit!", date: "5 Mar 2026", avatar: "🎮" },
  { name: "Tari J.", game: "Roblox", rating: 5, comment: "Trusted seller! Udah belasan kali beli robux disini", date: "4 Mar 2026", avatar: "⭐" },
  { name: "Galih W.", game: "Roblox", rating: 5, comment: "Beli robux buat main Blox Fruits, cepet masuknya!", date: "3 Mar 2026", avatar: "🍊" },
  { name: "Joko S.", game: "Roblox", rating: 5, comment: "Anak minta top up robux, disini paling murah!", date: "2 Mar 2026", avatar: "👨" },
  { name: "Sari N.", game: "Roblox", rating: 4, comment: "Beli robux pertama kali, prosesnya mudah banget", date: "1 Mar 2026", avatar: "🎁" },
  { name: "Wahyu D.", game: "Roblox", rating: 5, comment: "Lapak Robux emang paling oke buat beli robux!", date: "28 Feb 2026", avatar: "👍" },
  { name: "Riko A.", game: "Roblox", rating: 5, comment: "Robux 800 cuma 100rb, dimana lagi coba? Mantap!", date: "27 Feb 2026", avatar: "💰" },
  { name: "Tasya M.", game: "Roblox", rating: 5, comment: "Anak-anak seneng banget, bisa beli limited item di Roblox", date: "26 Feb 2026", avatar: "🎀" },
  { name: "Faisal B.", game: "Roblox", rating: 5, comment: "Beli robux buat Adopt Me, proses kilat!", date: "25 Feb 2026", avatar: "🐾" },
  { name: "Lina P.", game: "Roblox", rating: 4, comment: "Prosesnya manual tapi tetep cepet, paling lama 15 menit", date: "24 Feb 2026", avatar: "⏳" },
  { name: "Ardi N.", game: "Roblox", rating: 5, comment: "Udah 20x lebih beli robux disini, ga pernah ada masalah", date: "23 Feb 2026", avatar: "🔥" },
  { name: "Kiki R.", game: "Roblox", rating: 5, comment: "Robux masuk langsung, bisa bikin game sendiri di Roblox Studio!", date: "22 Feb 2026", avatar: "🛠️" },
  { name: "Yanti S.", game: "Roblox", rating: 5, comment: "Beli robux buat anak setiap minggu, harga stabil terus", date: "21 Feb 2026", avatar: "📅" },
  { name: "Imam T.", game: "Roblox", rating: 5, comment: "Premium Roblox + Robux, semua ada disini!", date: "20 Feb 2026", avatar: "👑" },
  { name: "Della F.", game: "Roblox", rating: 5, comment: "Beli robux pake uang jajan, harganya ramah di kantong!", date: "19 Feb 2026", avatar: "🪙" },
  { name: "Farhan G.", game: "Roblox", rating: 5, comment: "Top up robux tercepat yang pernah saya coba, 2 menit done!", date: "18 Feb 2026", avatar: "⚡" },
  { name: "Mila D.", game: "Roblox", rating: 4, comment: "Awalnya takut scam, ternyata beneran legit. Makasih!", date: "17 Feb 2026", avatar: "🛡️" },
  { name: "Rama K.", game: "Roblox", rating: 5, comment: "Gamepass Blox Fruits langsung kebeli, robux instan!", date: "16 Feb 2026", avatar: "⚔️" },
  { name: "Nurul H.", game: "Roblox", rating: 5, comment: "Harga robux disini paling bersaing, udah bandingin banyak", date: "15 Feb 2026", avatar: "📊" },
  { name: "Gilang Y.", game: "Roblox", rating: 5, comment: "Beli robux buat King Legacy, mantap prosesnya!", date: "14 Feb 2026", avatar: "🏴‍☠️" },

  // ═══════════════════════════════════════
  // FREE FIRE (65 testimoni)
  // ═══════════════════════════════════════
  { name: "Dimas F.", game: "Free Fire", rating: 5, comment: "Top up FF murah, diamond langsung masuk ke akun!", date: "10 Mar 2026", avatar: "🔫" },
  { name: "Rina A.", game: "Free Fire", rating: 5, comment: "Beli diamond buat beli bundle, harganya bersahabat banget", date: "9 Mar 2026", avatar: "💐" },
  { name: "Kevin T.", game: "Free Fire", rating: 5, comment: "Proses gak sampe 5 menit, top up FF paling cepet!", date: "8 Mar 2026", avatar: "🎯" },
  { name: "Lina D.", game: "Free Fire", rating: 4, comment: "Murah dan cepet, next time pasti top up disini lagi", date: "7 Mar 2026", avatar: "🌺" },
  { name: "Arief N.", game: "Free Fire", rating: 5, comment: "Udah 3x transaksi, semuanya lancar jaya!", date: "6 Mar 2026", avatar: "💪" },
  { name: "Indah M.", game: "Free Fire", rating: 5, comment: "Temen yang rekomendasiin, ternyata beneran murah!", date: "5 Mar 2026", avatar: "🌻" },
  { name: "Fikri Z.", game: "Free Fire", rating: 5, comment: "Top up diamond FF buat event, murah dan cepet!", date: "4 Mar 2026", avatar: "🎉" },
  { name: "Agus M.", game: "Free Fire", rating: 5, comment: "Top up lancar, harga bersaing, pokoknya the best!", date: "3 Mar 2026", avatar: "🏆" },
  { name: "Tono W.", game: "Free Fire", rating: 5, comment: "Beli elite pass tiap season disini, harga paling oke", date: "2 Mar 2026", avatar: "🎖️" },
  { name: "Niken S.", game: "Free Fire", rating: 4, comment: "Diamond masuk agak lama pas weekend, tapi tetep masuk kok", date: "1 Mar 2026", avatar: "📱" },
  { name: "Eko B.", game: "Free Fire", rating: 5, comment: "Top up FF 100 diamond cuma 15rb, murah parah sih!", date: "28 Feb 2026", avatar: "💸" },
  { name: "Siska L.", game: "Free Fire", rating: 5, comment: "Beli diamond buat gacha incubator, hasilnya dapet skin bagus!", date: "27 Feb 2026", avatar: "🎰" },
  { name: "Rahman D.", game: "Free Fire", rating: 5, comment: "Member FF sejak lama, top up selalu disini", date: "26 Feb 2026", avatar: "🔒" },
  { name: "Wati K.", game: "Free Fire", rating: 5, comment: "Diamond FF masuk instant, langsung bisa push ranked!", date: "25 Feb 2026", avatar: "🏅" },
  { name: "Jihan P.", game: "Free Fire", rating: 5, comment: "Harga stabil, ga pernah naik-naik, suka banget!", date: "24 Feb 2026", avatar: "📈" },
  { name: "Bagus H.", game: "Free Fire", rating: 5, comment: "Diamond FF 520 cuma 70rb, murah banget!", date: "23 Feb 2026", avatar: "💰" },
  { name: "Yeni R.", game: "Free Fire", rating: 5, comment: "Top up buat beli MP40 Evo Gun, prosesnya kilat!", date: "22 Feb 2026", avatar: "⚡" },
  { name: "Asep K.", game: "Free Fire", rating: 5, comment: "Udah langganan 6 bulan, ga pernah ada masalah sama sekali", date: "21 Feb 2026", avatar: "📅" },
  { name: "Rini W.", game: "Free Fire", rating: 4, comment: "Pertama kali coba, ternyata beneran aman dan cepet", date: "20 Feb 2026", avatar: "🛡️" },
  { name: "Alfian S.", game: "Free Fire", rating: 5, comment: "Beli membership mingguan FF disini, harga paling murah!", date: "19 Feb 2026", avatar: "🎫" },
  { name: "Putri H.", game: "Free Fire", rating: 5, comment: "Top up diamond buat beli emote baru, seru banget!", date: "18 Feb 2026", avatar: "💃" },
  { name: "Lukman A.", game: "Free Fire", rating: 5, comment: "Admin fast respond, diamond masuk kurang dari 2 menit!", date: "17 Feb 2026", avatar: "⏱️" },
  { name: "Maya S.", game: "Free Fire", rating: 5, comment: "Beli diamond buat gift ke pacar, prosesnya gampang", date: "16 Feb 2026", avatar: "🎁" },
  { name: "Wahid T.", game: "Free Fire", rating: 5, comment: "Harga diamond 2180 paling murah disini, mantap!", date: "15 Feb 2026", avatar: "💎" },
  { name: "Santi M.", game: "Free Fire", rating: 4, comment: "Proses sekitar 5 menit tapi hasilnya oke, diamond masuk", date: "14 Feb 2026", avatar: "✅" },
  { name: "Irfan B.", game: "Free Fire", rating: 5, comment: "Top up FF pake QRIS gampang banget, scan langsung masuk!", date: "13 Feb 2026", avatar: "📲" },
  { name: "Dewi A.", game: "Free Fire", rating: 5, comment: "Diamond buat spin lucky royale, top up disini paling worth!", date: "12 Feb 2026", avatar: "🎰" },
  { name: "Candra P.", game: "Free Fire", rating: 5, comment: "Beli weekly membership selalu disini, murah dan cepet", date: "11 Feb 2026", avatar: "🗓️" },
  { name: "Nur F.", game: "Free Fire", rating: 5, comment: "Rekomendasi dari temen guild, ternyata beneran bagus!", date: "10 Feb 2026", avatar: "👥" },
  { name: "Heru W.", game: "Free Fire", rating: 5, comment: "Top up diamond buat push Heroic, langsung masuk!", date: "9 Feb 2026", avatar: "🏆" },
  { name: "Vina L.", game: "Free Fire", rating: 5, comment: "Diamond FF 100 murah banget, cocok buat top up kecil", date: "8 Feb 2026", avatar: "🪙" },
  { name: "Rizal A.", game: "Free Fire", rating: 5, comment: "Udah 15x transaksi, semuanya aman dan lancar!", date: "7 Feb 2026", avatar: "🔥" },
  { name: "Anita D.", game: "Free Fire", rating: 4, comment: "Admin ramah banget, dibantu sampe diamond masuk", date: "6 Feb 2026", avatar: "😊" },
  { name: "Farid M.", game: "Free Fire", rating: 5, comment: "Beli diamond FF buat event Valentine, harganya oke!", date: "5 Feb 2026", avatar: "💝" },
  { name: "Lilis S.", game: "Free Fire", rating: 5, comment: "Top up via transfer bank BCA, proses tetep cepet!", date: "4 Feb 2026", avatar: "🏦" },
  { name: "Andi R.", game: "Free Fire", rating: 5, comment: "Beli elite pass + diamond sekaligus, hemat banget!", date: "3 Feb 2026", avatar: "🎮" },
  { name: "Tuti N.", game: "Free Fire", rating: 5, comment: "Diamond langsung masuk, ga perlu nunggu lama. Top!", date: "2 Feb 2026", avatar: "⚡" },
  { name: "Gunawan H.", game: "Free Fire", rating: 5, comment: "Harga diamond FF disini paling kompetitif, udah bandingin!", date: "1 Feb 2026", avatar: "📊" },
  { name: "Kartika W.", game: "Free Fire", rating: 5, comment: "Beli diamond buat koleksi skin, harganya murah pol!", date: "31 Jan 2026", avatar: "👗" },
  { name: "Dedi P.", game: "Free Fire", rating: 4, comment: "Proses manual tapi admin cepet, diamond masuk aman", date: "30 Jan 2026", avatar: "🤝" },
  { name: "Winda B.", game: "Free Fire", rating: 5, comment: "Top up diamond buat custom room, prosesnya instan!", date: "29 Jan 2026", avatar: "🏠" },
  { name: "Saiful A.", game: "Free Fire", rating: 5, comment: "Beli diamond 1080 murah banget, langsung bisa gacha!", date: "28 Jan 2026", avatar: "🎲" },
  { name: "Ratih K.", game: "Free Fire", rating: 5, comment: "Admin online 24 jam, top up tengah malam juga bisa!", date: "27 Jan 2026", avatar: "🌙" },
  { name: "Yusuf M.", game: "Free Fire", rating: 5, comment: "Pembayaran via ShopeePay juga bisa, super lengkap!", date: "26 Jan 2026", avatar: "🛒" },
  { name: "Intan S.", game: "Free Fire", rating: 5, comment: "Diamond buat beli pet baru, top up disini paling oke!", date: "25 Jan 2026", avatar: "🐱" },
  { name: "Bambang T.", game: "Free Fire", rating: 5, comment: "Udah rekomendasi ke satu guild, semua pada puas!", date: "24 Jan 2026", avatar: "🏰" },
  { name: "Sari D.", game: "Free Fire", rating: 4, comment: "Pertama kali top up online, ternyata gampang banget disini", date: "23 Jan 2026", avatar: "🌟" },
  { name: "Oka W.", game: "Free Fire", rating: 5, comment: "Top up buat beli bundle baru, harganya bersahabat!", date: "22 Jan 2026", avatar: "👕" },
  { name: "Fitria R.", game: "Free Fire", rating: 5, comment: "Diamond masuk cepet, bisa langsung main ranked!", date: "21 Jan 2026", avatar: "🎯" },
  { name: "Hendro B.", game: "Free Fire", rating: 5, comment: "Langganan top up FF disini, ga mau pindah ke lain!", date: "20 Jan 2026", avatar: "🔒" },
  { name: "Lusi M.", game: "Free Fire", rating: 5, comment: "Harga 310 diamond cuma 40rb, paling murah se-Indonesia!", date: "19 Jan 2026", avatar: "💸" },
  { name: "Prasetyo H.", game: "Free Fire", rating: 5, comment: "Top up FF via GoPay bisa, prosesnya cuma 1 menit!", date: "18 Jan 2026", avatar: "💚" },
  { name: "Aisyah K.", game: "Free Fire", rating: 5, comment: "Beli diamond buat event anniversary FF, murah banget!", date: "17 Jan 2026", avatar: "🎂" },
  { name: "Roni G.", game: "Free Fire", rating: 4, comment: "Sempet ragu awalnya, tapi sekarang jadi pelanggan tetap!", date: "16 Jan 2026", avatar: "✨" },
  { name: "Mega P.", game: "Free Fire", rating: 5, comment: "Top up diamond 520 buat beli gloo wall skin, worth it!", date: "15 Jan 2026", avatar: "🧱" },
  { name: "Joko M.", game: "Free Fire", rating: 5, comment: "Admin sabar banget ngebantu, diamond masuk dengan aman!", date: "14 Jan 2026", avatar: "😇" },
  { name: "Tantri S.", game: "Free Fire", rating: 5, comment: "Beli diamond tiap minggu disini, harga konsisten murah", date: "13 Jan 2026", avatar: "📆" },
  { name: "Udin A.", game: "Free Fire", rating: 5, comment: "Top up FF tercepat! Diamond masuk sebelum selesai makan 😂", date: "12 Jan 2026", avatar: "🍜" },
  { name: "Pipit R.", game: "Free Fire", rating: 5, comment: "Beli level up pass + diamond, paket hemat banget!", date: "11 Jan 2026", avatar: "📦" },
  { name: "Dimas W.", game: "Free Fire", rating: 5, comment: "Udah 30x lebih top up, ga pernah sekalipun gagal!", date: "10 Jan 2026", avatar: "💯" },
  { name: "Nurhayati B.", game: "Free Fire", rating: 5, comment: "Beli diamond buat anak, prosesnya mudah dan aman!", date: "9 Jan 2026", avatar: "👩" },
  { name: "Ferdi K.", game: "Free Fire", rating: 5, comment: "Top up diamond buat turnamen guild, admin fast banget!", date: "8 Jan 2026", avatar: "⚔️" },
  { name: "Silvi N.", game: "Free Fire", rating: 4, comment: "Harga naik dikit pas event tapi masih lebih murah dari yang lain", date: "7 Jan 2026", avatar: "📉" },
  { name: "Anto J.", game: "Free Fire", rating: 5, comment: "Diamond masuk instan, langsung bisa spin magic cube!", date: "6 Jan 2026", avatar: "🎰" },
  { name: "Wulan P.", game: "Free Fire", rating: 5, comment: "The best top up FF! Cepet, murah, aman. Ga ada duanya!", date: "5 Jan 2026", avatar: "🥇" },

  // ═══════════════════════════════════════
  // PUBG MOBILE (15 testimoni)
  // ═══════════════════════════════════════
  { name: "Fajar D.", game: "PUBG Mobile", rating: 5, comment: "UC PUBG murah! Bisa beli Royale Pass sekarang 🔥", date: "10 Mar 2026", avatar: "🔥" },
  { name: "Devi S.", game: "PUBG Mobile", rating: 5, comment: "Top up UC cepet, admin fast respond banget", date: "9 Mar 2026", avatar: "🎖️" },
  { name: "Ahmad B.", game: "PUBG Mobile", rating: 4, comment: "Pertama beli UC disini, beneran masuk dan aman", date: "8 Mar 2026", avatar: "🛡️" },
  { name: "Wulan C.", game: "PUBG Mobile", rating: 5, comment: "Harga UC paling worth it, udah compare sama yang lain", date: "7 Mar 2026", avatar: "💜" },
  { name: "Eko P.", game: "PUBG Mobile", rating: 5, comment: "Fast delivery! UC langsung masuk, mantap!", date: "6 Mar 2026", avatar: "🏅" },
  { name: "Raka H.", game: "PUBG Mobile", rating: 5, comment: "Selalu puas top up disini, ga pernah mengecewakan", date: "5 Mar 2026", avatar: "🎖️" },
  { name: "Dani O.", game: "PUBG Mobile", rating: 5, comment: "UC murah, bisa beli semua skin incaran!", date: "4 Mar 2026", avatar: "🔫" },
  { name: "Hendri L.", game: "PUBG Mobile", rating: 5, comment: "Royale Pass tiap season beli disini, worth banget!", date: "3 Mar 2026", avatar: "🎫" },
  { name: "Putri W.", game: "PUBG Mobile", rating: 4, comment: "UC masuk sekitar 10 menit, masih oke lah", date: "2 Mar 2026", avatar: "⏰" },
  { name: "Andi F.", game: "PUBG Mobile", rating: 5, comment: "Top up UC buat beli crate, harga disini paling murah!", date: "1 Mar 2026", avatar: "📦" },
  { name: "Mega R.", game: "PUBG Mobile", rating: 5, comment: "PUBG New State juga bisa top up disini, keren!", date: "28 Feb 2026", avatar: "🌟" },
  { name: "Taufik A.", game: "PUBG Mobile", rating: 5, comment: "Beli UC 600 murah banget, langsung bisa RP!", date: "27 Feb 2026", avatar: "💰" },
  { name: "Sari M.", game: "PUBG Mobile", rating: 5, comment: "Admin ramah, proses cepet, harga bersahabat. 10/10!", date: "26 Feb 2026", avatar: "💯" },
  { name: "Rizal K.", game: "PUBG Mobile", rating: 5, comment: "Udah setahun langganan, ga pernah ada kendala apapun", date: "25 Feb 2026", avatar: "📆" },
  { name: "Dina S.", game: "PUBG Mobile", rating: 5, comment: "Top up UC tengah malam juga dilayani, mantap admin!", date: "24 Feb 2026", avatar: "🌃" },

  // ═══════════════════════════════════════
  // GENSHIN IMPACT (15 testimoni)
  // ═══════════════════════════════════════
  { name: "Yuki N.", game: "Genshin Impact", rating: 5, comment: "Top up Genesis Crystal murah, bisa gacha banyak!", date: "10 Mar 2026", avatar: "⚡" },
  { name: "Sarah L.", game: "Genshin Impact", rating: 5, comment: "Welkin Moon selalu beli disini, harga paling oke!", date: "9 Mar 2026", avatar: "🌙" },
  { name: "Rio G.", game: "Genshin Impact", rating: 5, comment: "Beli blessing of welkin moon, proses instan!", date: "8 Mar 2026", avatar: "🌊" },
  { name: "Mira T.", game: "Genshin Impact", rating: 4, comment: "Genesis crystal langsung masuk, bisa pull character baru", date: "7 Mar 2026", avatar: "🦋" },
  { name: "Hendra K.", game: "Genshin Impact", rating: 5, comment: "Trusted! Udah berkali-kali top up crystal disini", date: "6 Mar 2026", avatar: "🗡️" },
  { name: "Tiara W.", game: "Genshin Impact", rating: 5, comment: "Top up crystal cepet, bisa gacha banner baru!", date: "5 Mar 2026", avatar: "✨" },
  { name: "Karina F.", game: "Genshin Impact", rating: 5, comment: "Crystal murah, CS ramah, proses cepat. 10/10!", date: "4 Mar 2026", avatar: "💯" },
  { name: "Reza M.", game: "Genshin Impact", rating: 5, comment: "Top up 6480 crystal, harga disini paling murah!", date: "3 Mar 2026", avatar: "💎" },
  { name: "Amel S.", game: "Genshin Impact", rating: 5, comment: "Dapet Zhongli berkat top up disini, makasih banget!", date: "2 Mar 2026", avatar: "🪨" },
  { name: "Fahmi D.", game: "Genshin Impact", rating: 4, comment: "Proses agak lama pas server rame, tapi crystal tetep masuk", date: "1 Mar 2026", avatar: "⏳" },
  { name: "Luna P.", game: "Genshin Impact", rating: 5, comment: "Beli battle pass + welkin, paket combo hemat banget!", date: "28 Feb 2026", avatar: "🎮" },
  { name: "Yudha A.", game: "Genshin Impact", rating: 5, comment: "Crystal langsung masuk, gacha Nahida dapet! Hoki!", date: "27 Feb 2026", avatar: "🍀" },
  { name: "Cantika R.", game: "Genshin Impact", rating: 5, comment: "Selalu top up disini tiap banner baru, harga stabil", date: "26 Feb 2026", avatar: "🌸" },
  { name: "Iqbal W.", game: "Genshin Impact", rating: 5, comment: "Welkin moon 50rb aja, dimana lagi ada semurah ini?", date: "25 Feb 2026", avatar: "🌟" },
  { name: "Sherly B.", game: "Genshin Impact", rating: 5, comment: "Top up crystal buat anniv event, prosesnya super cepet!", date: "24 Feb 2026", avatar: "🎂" },
];

export const totalReviews = testimonials.length;
export const avgRating = (testimonials.reduce((sum, t) => sum + t.rating, 0) / totalReviews).toFixed(1);

export const gameFilters = ["Semua", "Mobile Legends", "Free Fire", "Roblox", "PUBG Mobile", "Genshin Impact"];
